var grammar = tracery.createGrammar({
    'origin':                   '[#lineage!#]You, #protagonist#, were raised by #your parents?# #in your childhood home#. #Now you live somewhere#, where you #do an activity#. #fact about you#',
    'lineage!':                 '[your name?:#dragon name#][your parents?:#your parents#]',
    'protagonist':              '#your name?# the #dragon species#',
    'your parents':             ['#two parents#', '#two parents#', '#two parents#', '#your parents sub#'],
    'two parents':              '#your parent# and #your parent#',
    'your parents sub':         ['#your parent#', '#your parent#, #your parent#, and #your parent#', 'a commune of #commune species#'],
    'commune species':          ['fire lizards', '[your name?:#gnome name#]gnomes', 'humans', '[your name?:#kobold name#]kobolds'],
    'your parent':              '#dragon name# the #dragon species#',
    'Now you live somewhere':  ['Now you live #in your lair#', 'Now you live #in your lair#', 'Now you live #in your lair#', 'You remain there still'],
    'in your childhood home':   '#in a place#',
    'in your lair':             '#in a place#',

    /* Species */

    'dragon species': '#maybe two-headed##dragon species_#',
    'maybe two-headed': ['', '', '', '', '', '', '', '#maybe two-headed_#'],
    'maybe two-headed_': ['', '', '', '', '', '', '', 'two-headed '],
    'dragon species_': [
        '#common species#',
        '#common species#',
        '#common species#',
        '#common species#',
        '#common species#',
        '#common species#',
        '#common species#',
        '#dragon species__#',
    ],
    'dragon species__': [
        '#common species#',
        '#common species#',
        '#common species#',
        '#common species#',
        '#common species#',
        '#common species#',
        '#common species#',
        '#two-tone dragon#',
    ],
    'common species': [
        '#color# dragon',
        '#color# dragon',
        '#color# dragon',
        '#color# dragon',
        '#mineral# dragon',
        '#mineral# dragon',
        '#mineral# dragon',
        '#unusual dragon species#',
    ],
    'two-tone dragon': [
        '#color# and #color# dragon',
        '#color# and #color# dragon',
        '#color# and #color# dragon',
        '#mineral# and #mineral# dragon',
        '#mineral# and #mineral# dragon',
    ],
    'color': [
        '<span class="black">black</span>',
        '<span class="blue">blue</span>',
        '<span class="brown">brown</span>',
        '<span class="cyan">cyan</span>',
        '<span class="grey">grey</span>',
        '<span class="green">green</span>',
        '<span class="magenta">magenta</span>',
        '<span class="purple">purple</span>',
        '<span class="red">red</span>',
        '<span class="yellow">yellow</span>',
        '<span class="white">white</span>',
    ],
    'mineral': [
        '#gem#',
        '#metal#',
    ],
    'gem': [
        '<span class="amethyst">amethyst</span>',
        '<span class="diamond">diamond</span>',
        '<span class="emerald">emerald</span>',
        '<span class="ruby">ruby</span>',
        '<span class="sapphire">sapphire</span>',
        '<span class="topaz">topaz</span>',
        '#unusual gem#',
    ],
    'unusual gem': [
        '<span class="agate">agate</span>',
        '<span class="aquamarine">aquamarine</span>',
        '<span class="bismuth bismuth-#bismuth color#" style="background-image: linear-gradient(to right, #bismuth color#, #bismuth color#, #bismuth color#);">bismuth</span>',
        '<span class="bloodstone">bloodstone</span>',
        '<span class="coal">coal</span>',
        '<span class="garnet">garnet</span>',
        '<span class="jade">jade</span>',
        '<span class="jasper">jasper</span>',
        '<span class="lapislazuli">lapislazuli</span>',
        '<span class="moonstone">moonstone</span>',
        '<span class="obsidian">obsidian</span>',
        '<span class="onyx">onyx</span>',
        '<span class="opal">opal</span>',
        '<span class="pearl">pearl</span>',
        '<span class="peridot">peridot</span>',
        '<span class="quartz">quartz</span>',
        '<span class="spinel">spinel</span>',
        '<span class="turqoise">turquoise</span>',
    ],
    'bismuth color': [
        'pink',
        'orange',
        'yellow',
        'green',
        'blue',
        'indigo',
        'violet',
    ],
    'metal': [
        '<span class="brass">brass</span>',
        '<span class="bronze">bronze</span>',
        '<span class="copper">copper</span>',
        '<span class="gold">gold</span>',
        '<span class="iron">iron</span>',
        '<span class="silver">silver</span>',
        '#unusual metal#',
    ],
    'unusual metal': [
        '<span class="mercury">mercury</span>',
        '<span class="mithril">mithril</span>',
        '<span class="platinum">platinum</span>',
        '<span class="steel">steel</span>',
        '<span class="titanium">titanium</span>',
    ],
    'unusual dragon species': [
        'fairy dragon',
        'fire lizard',
        '<span class="galaxy">galaxy</span> dragon',
        '#color# glitter dragon',
        'pseudodragon',
        '<span class="rainbow">rainbow</span> dragon',
        'translucent dragon',
    ],

    /* Names */

    'dragon name': '#dragon name sub.capitalize#',
    'dragon name sub': [
        '#dragon name part##dragon name final vowel#',
        '#dragon name part##dragon name final part#',
        '#dragon name part##dragon name sub#',
    ],
    'dragon name part':             '#dragon name vowel##dragon name consonant#',
    'dragon name final part':       '#dragon name vowel##dragon name final consonant#',
    'dragon name consonant':        ['b', 'c', 'm', 'r', 's', 'sh', 't', 'th', 'v', 'w', 'y', 'z'],
    'dragon name final consonant':  ['b', 'c', 'm', 'r', 's', 'sh', 't', 'th'],
    'dragon name vowel':            ['a', 'aa', 'æ', 'au', 'e', 'ea', 'i', 'ii', 'o', 'u', 'y'],
    'dragon name final vowel':      ['a',       'æ',       'e', 'ea',                 'u'],

    'gnome name': "#gnome first name# #gnome last name#",
    'gnome first name': '#gnome noun.capitalize#',
    'gnome last name': ['#gnome noun.capitalize##gnome profession#'],
    'gnome noun': [
        'bolt',
        'cable',
        'cog',
        'crane',
        'drill',
        'gear',
        'pipe',
        'pulley',
        'scaffold',
        'widget',
        'winch',
        'wrench',
    ],
    'gnome profession': [
        'breaker',
        'builder',
        'fixer',
        'grinder',
        'hauler',
        'layer',
        'loader',
        'maker',
        'miner',
        'plumber',
        'smith',
        'tinker',
    ],

    'kobold name': '#kobold name nucleus.capitalize##kobold name end#',
    'kobold name nucleus': '#kobold consonant##kobold vowel#',
    'kobold name end': ['#kobold consonant#', '#kobold name nucleus#'],
    'kobold consonant': ['b', 'k', 'n', 'r', 't', 'x', 'z'],
    'kobold vowel': ['a', 'e', 'i', 'o', 'u', '#kobold long vowel#', '#kobold iotated vowel#'],
    'kobold long vowel': ['aa', 'ee', 'oo', 'uu'],
    'kobold iotated vowel': ['ya', 'ye', 'yo', 'yu'],

    /* Places */

    'in a place':       'in #prefixed place.a#',
    'prefixed place':   '#place prefix# #place#',
    'place prefix': [
        'abandoned',
        'burnt',
        'flooded',
        'forgotten',
        'frozen',
        'haunted',
        'remote',
        'uncharted',
    ],
    'place': [
        'cave',
        '#dungeon#',
        '#forest#',
        'grotto',
        '#house#',
        'mountain',
        'swamp',
        '#town#',
        'valley',
        '#active or inactive# volcano',
    ],
    'dungeon': [
        'dungeon',
        'shrine',
        'temple',
    ],
    'forest': [
        'clearing',
        'forest',
        'grove',
        'mushroom forest',
        'wood',
    ],
    'house': [
        'cottage',
        'house',
        'hut',
        'mansion',
        'shack',
    ],
    'town': [
        'city',
        'hamlet',
        'metropolis',
        'thorp',
        'town',
        'village',
    ],
    'active or inactive': [
        'active',
        'inactive',
    ],

    /* Activities */

    'do an activity': [
        'guard your hoard of #hoard items#',
        '#make something#',
        'pass the days #doing a pastime#',
        'study #subject of study#',
    ],
    'hoard items': [
        '#art items#',
        'gems',
        'gold',
        'magical artifacts',
        '#unusual hoard items#',
    ],
    'art items': [
        'dolls',
        'figurines',
        'paintings',
        'sonnets',
        'statues',
    ],
    'unusual hoard items': [
        'baked goods',
        '#pet species# clothing',
        'cutlery',
        'napkins',
        'plushies',
        'rocks',
    ],
    'make something': [
        'knit #knitted items#',
        'sculpt #sculpting material#',
        'write #novel type# novels',
    ],
    'knitted items': [
        'blankets',
        'cozies',
        'hats',
        'rugs',
        'scarves',
        'shawls',
        'socks',
        'sweaters',
        'tapestries',
    ],
    'sculpting material': [
        'clay',
        'dirt',
        'fire',
        'flesh',
        'ice',
        'wood',
        '#mineral#',
    ],
    'doing a pastime': [
        'admiring the local architecture',
        'cloud watching',
        'counting your treasures',
        'doing nothing of note',
        'idly pondering',
        'napping',
        'reading #reading material#',
    ],
    'reading material': [
        '#novel type# novels',
        'religious texts',
        'spellbooks',
        'town papers',
        'white papers',
    ],
    'novel type': [
        'bawdy',
        'cheap',
        'fantastical',
        'trashy',
        'weird',
    ],
    'subject of study': [
        'animal husbandry',
        'art',
        'botany',
        '#combat#',
        'history',
        '#magic#',
        'mathematics',
        'music',
        'philosophy',
        '#theater#',
        'tinkering',
        '#unusual subject of study#',
    ],
    'combat': [
        'archery',
        'fencing',
        'martial arts',
        'siegecraft',
        'swordsmanship',
        'wrestling',
    ],
    'magic': [
        'abjuration',
        'alchemy',
        'arcana',
        'blood magic',
        'conjuration',
        'curses',
        'dark magic',
        'demon summoning',
        'divination',
        'elemental magic',
        'enchantment',
        'glamor',
        'healing',
        'herbalism',
        'hexes',
        'illusion',
        'magic',
        'necromancy',
        'poisons',
        'prayer magic',
        'protection magic',
        'runes',
        'shadow magic',
        'transmutation',
    ],
    'theater': [
        'opera',
        'playwrighting',
        'prop design',
        'soliloquys',
        'theater',
    ],
    'unusual subject of study': [
        'agriculture',
        'animal training',
        'architecture',
        'astrology',
        'astronomy',
        'blacksmithing',
        'calligraphy',
        'cartography',
        'chemistry',
        'falconry',
        'haberdashery',
        'heraldry',
        'husbandry',
        'physics',
        'psychology',
        'surgery',
    ],

    /* Facts */

    'fact about you': [
        'You are known for your #reknowned quality#.',
        'You keep #pet species.a# as a pet.',
        'Your most prized possession is #your most prized possession#.',
        'Your scales are #scale quality#.',
    ],
    'reknowned quality': [
        'appetite',
        'cunning',
        'ferocity',
        'greed',
        'immense size',
        'kindheartedness',
        'knowledge of forgotten lore',
        'liking of #hoard items#',
        'magnanimity',
        'mercy',
        'mighty roar',
        'penchant for violence',
        'reclusiveness',
        'sense of justice',
        'short-temperedness',
        'swift retribution',
        'talkativeness',
        'unpredictability',
    ],
    'pet species': [
        '#bird#',
        'cat',
        'fire lizard',
        'gnome',
        'human',
        'kobold',
        '#element# elemental',
    ],
    'bird': [
        '#corvid#',
        'parakeet',
        'parrot',
        'pigeon',
        'snipe',
    ],
    'corvid': [
        'bluejay',
        'crow',
        'magpie',
        'raven',
    ],
    'element': [
        'air',
        'earth',
        'fire',
        'water',
        'wood',
        '#unusual element#',
    ],
    'unusual element': [
        'cloud',
        'ice',
        'lightning',
        'magma',
        'mud',
        'smog',
        'steam',
    ],
    'your most prized possession': [
        'a finely cut #gem#',
        'a set of fine #fine items#',
        'a tome of lost knowledge',
        'the skull of #slayer species.a# who failed to slay you',
        'your wits',
    ],
    'fine items': [
        '#unusual hoard items#',
        '#knitted items#',
    ],
    'slayer species': [
        '#dragon species#',
        'human',
    ],
    'scale quality': [
        'as hard as #mineral#',
        'scarred from many battles',
        'smooth to the touch',
    ],
})

grammar.addModifiers(baseEngModifiers)
